packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  msw: false
catalog:
  '@biomejs/biome': ^2.5.12
  '@dnd-kit/react': ^0.5.0  
  es-toolkit: ^1.52.0
  usehooks-ts: ^3.1.1
  zod: ^4.4.3
  zustand: ^5.0.15